import fs from "node:fs";
import type { CollectionEntry } from "astro:content";
import { defaultLang, localizePath, LOCALES, type Lang } from "../i18n/utils";

export type BlogEntry = CollectionEntry<"blog">;

export function slugifyTag(tag: string): string {
  return tag
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Language of a post. Non-default languages live in a folder named after the
 * locale (e.g. src/content/blog/pl/foo.mdx → "pl"). Frontmatter `lang` is used
 * as a fallback.
 */
export function getPostLang(post: BlogEntry): Lang {
  const prefix = post.id.split("/")[0];
  if (prefix === "pl") return "pl";
  return (post.data.lang ?? defaultLang) as Lang;
}

/**
 * Stable slug shared by every translation of a post. Derived by stripping the
 * leading language folder from the file id (e.g. "pl/redis" → "redis"), unless
 * an explicit translationKey is provided in frontmatter.
 */
export function getPostSlug(post: BlogEntry): string {
  return post.data.translationKey ?? post.id.replace(/^(pl|en)\//, "");
}

/** Localized URL for a post, e.g. "/blog/redis/" or "/pl/blog/redis/". */
export function getPostUrl(post: BlogEntry): string {
  const lang = getPostLang(post);
  return localizePath(`/blog/${getPostSlug(post)}/`, lang);
}

export function filterByLang(posts: BlogEntry[], lang: Lang): BlogEntry[] {
  return posts.filter((post) => getPostLang(post) === lang);
}

export function getReadingTime(body?: string): number {
  if (!body) return 1;
  const words = body.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 200));
}

export function sortByDateDesc(posts: BlogEntry[]): BlogEntry[] {
  return [...posts].sort(
    (a, b) => b.data.pubDate.valueOf() - a.data.pubDate.valueOf()
  );
}

export function getRelatedPosts(
  current: BlogEntry,
  all: BlogEntry[],
  limit = 3
): BlogEntry[] {
  const currentLang = getPostLang(current);
  const currentTags = new Set((current.data.tags ?? []).map(slugifyTag));
  const others = filterByLang(all, currentLang).filter((p) => p.id !== current.id);

  const scored = others
    .map((post) => {
      const overlap = (post.data.tags ?? []).filter((tag) =>
        currentTags.has(slugifyTag(tag))
      ).length;
      return { post, overlap };
    })
    .sort((a, b) => {
      if (b.overlap !== a.overlap) return b.overlap - a.overlap;
      return b.post.data.pubDate.valueOf() - a.post.data.pubDate.valueOf();
    });

  const related = scored.filter((s) => s.overlap > 0).map((s) => s.post);
  if (related.length >= limit) return related.slice(0, limit);

  const fill = scored.filter((s) => s.overlap === 0).map((s) => s.post);
  return [...related, ...fill].slice(0, limit);
}

/** Group every post by its shared slug so we can look up translations. */
export function getTranslationsMap(
  posts: BlogEntry[]
): Map<string, Partial<Record<Lang, BlogEntry>>> {
  const map = new Map<string, Partial<Record<Lang, BlogEntry>>>();
  for (const post of posts) {
    const key = getPostSlug(post);
    const entry = map.get(key) ?? {};
    entry[getPostLang(post)] = post;
    map.set(key, entry);
  }
  return map;
}

type PostLinkProp = { url: string; title: string };
type RelatedProp = { url: string; title: string; description: string };

export type PostPageProps = {
  post: BlogEntry;
  prevPost?: PostLinkProp;
  nextPost?: PostLinkProp;
  relatedPosts: RelatedProp[];
  readingTime: number;
  alternates: Partial<Record<Lang, string>>;
  langHrefs: Partial<Record<Lang, string>>;
  ogImage?: string;
};

/**
 * Social-preview image for a post. LinkedIn does not reliably render WebP
 * og:image, so posts use the JPEG copies generated by `pnpm og` into
 * public/og/. Falls back to the site default when none was generated.
 */
export function getOgImagePath(slug: string): string | undefined {
  return fs.existsSync(`public/og/${slug}.jpg`) ? `/og/${slug}.jpg` : undefined;
}

/**
 * Build getStaticPaths entries for a single language's blog posts, including
 * localized prev/next/related links and hreflang/switcher targets.
 */
export function buildPostStaticPaths(allPosts: BlogEntry[], lang: Lang) {
  const translations = getTranslationsMap(allPosts);
  const posts = sortByDateDesc(filterByLang(allPosts, lang));

  return posts.map((post, index) => {
    const newer = posts[index - 1];
    const older = posts[index + 1];

    const relatedPosts: RelatedProp[] = getRelatedPosts(post, allPosts, 3).map(
      (related) => ({
        url: getPostUrl(related),
        title: related.data.title,
        description: related.data.description,
      })
    );

    const slug = getPostSlug(post);
    const group = translations.get(slug) ?? {};
    const alternates: Partial<Record<Lang, string>> = {};
    const langHrefs: Partial<Record<Lang, string>> = {};
    for (const locale of LOCALES) {
      const translated = group[locale];
      if (translated) {
        const url = getPostUrl(translated);
        alternates[locale] = url;
        langHrefs[locale] = url;
      } else {
        // No translation: switcher falls back to that language's blog index.
        langHrefs[locale] = localizePath("/blog/", locale);
      }
    }

    const props: PostPageProps = {
      post,
      prevPost: older
        ? { url: getPostUrl(older), title: older.data.title }
        : undefined,
      nextPost: newer
        ? { url: getPostUrl(newer), title: newer.data.title }
        : undefined,
      relatedPosts,
      readingTime: getReadingTime(post.body),
      alternates,
      langHrefs,
      ogImage: getOgImagePath(slug),
    };

    return { params: { slug }, props };
  });
}

export type TagPageProps = {
  tag: string;
  taggedPosts: BlogEntry[];
  alternates: Partial<Record<Lang, string>>;
  langHrefs: Partial<Record<Lang, string>>;
};

/**
 * Build getStaticPaths entries for a single language's tag pages. A tag that
 * has no posts in the other locale gets no hreflang alternate there, and the
 * language switcher falls back to that locale's blog index instead of a 404.
 */
export function buildTagStaticPaths(allPosts: BlogEntry[], lang: Lang) {
  const posts = filterByLang(allPosts, lang);
  const tagSlugsByLang = new Map<Lang, Set<string>>(
    LOCALES.map((locale) => [
      locale,
      new Set(getAllTags(filterByLang(allPosts, locale)).map((t) => t.slug)),
    ])
  );

  return getAllTags(posts).map(({ tag, slug }) => {
    const taggedPosts = sortByDateDesc(
      posts.filter((post) =>
        (post.data.tags ?? []).some((t) => slugifyTag(t) === slug)
      )
    );

    const alternates: Partial<Record<Lang, string>> = {};
    const langHrefs: Partial<Record<Lang, string>> = {};
    for (const locale of LOCALES) {
      if (tagSlugsByLang.get(locale)?.has(slug)) {
        const url = localizePath(`/blog/tags/${slug}/`, locale);
        alternates[locale] = url;
        langHrefs[locale] = url;
      } else {
        langHrefs[locale] = localizePath("/blog/", locale);
      }
    }

    const props: TagPageProps = { tag, taggedPosts, alternates, langHrefs };
    return { params: { tag: slug }, props };
  });
}

export function getAllTags(posts: BlogEntry[]): { tag: string; slug: string; count: number }[] {
  const counts = new Map<string, { tag: string; count: number }>();
  for (const post of posts) {
    for (const tag of post.data.tags ?? []) {
      const slug = slugifyTag(tag);
      const existing = counts.get(slug);
      if (existing) {
        existing.count += 1;
      } else {
        counts.set(slug, { tag, count: 1 });
      }
    }
  }
  return [...counts.entries()]
    .map(([slug, { tag, count }]) => ({ tag, slug, count }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag));
}
